/** Centralized route paths — UXMD-II screen routes (Build-1). */
export const ROUTES = {
  landing: "/",
  login: "/login",
  signup: "/signup",
  verifyEmail: "/verify-email",
  forgotPassword: "/forgot-password",
  resetPassword: "/reset-password",
  invite: (token: string) => `/invite/${token}`,
  onboarding: {
    welcome: "/onboarding",
    orientation: "/onboarding/orientation",
    workspace: "/onboarding/workspace",
    connect: "/onboarding/connect",
    initializing: "/onboarding/initializing",
    complete: "/onboarding/complete",
  },
  settings: {
    home: "/app/settings",
    account: "/app/settings/account",
    security: "/app/settings/security",
    mfa: "/app/settings/security/mfa",
    activity: "/app/settings/activity",
    automationPolicies: "/app/settings/automation-policies",
    advanced: "/app/settings/advanced",
    memory: "/app/settings/memory",
    sources: (workspaceId: string) => `/app/settings/workspace/${workspaceId}/sources`,
    goals: (workspaceId: string) => `/app/settings/workspace/${workspaceId}/goals`,
    notifications: "/app/settings/notifications",
    privacy: "/app/settings/privacy",
    appearance: "/app/settings/appearance",
    billing: "/app/settings/billing",
    integrations: "/app/settings/integrations",
    organization: "/app/settings/organization",
    organizationMembers: "/app/settings/organization/members",
    workspace: (workspaceId: string) => `/app/settings/workspace/${workspaceId}`,
    team: (workspaceId: string) => `/app/settings/workspace/${workspaceId}/team`,
  },
  app: {
    home: "/app",
    forbidden: "/forbidden",
    commandCenter: (workspaceId: string) => `/app/w/${workspaceId}/command-center`,
    workspaceModule: (workspaceId: string, segment: string) =>
      `/app/w/${workspaceId}/${segment}`,
  },
  profile: {
    home: "/app/profile",
    sessions: "/app/profile/sessions",
  },
  legal: {
    privacy: "/legal/privacy",
    terms: "/legal/terms",
    cookies: "/legal/cookies",
    aiTransparency: "/legal/ai-transparency",
    security: "/legal/security",
  },
} as const;
